### ISSUE TITLE
Downloading files from the new MDS with the Copernicusmarine Toolbox

### ISSUE THREAD

**Issue by AlfaAli** [nansencenter/NERSC-HYCOM-CICE#239]
The Motu-client no longer works.
 I will add scripts to fetch both the BIO/PHYS  files using the Copernicusmarine Toolbox  (CMT). 
A user guide about CMT can be found here: https://help.marine.copernicus.eu/en/articles/7970514-copernicus-marine-toolbox-installation

**Comment by AlfaAli** [comment]
You need to specify the starting and end dates as well as your credential.

**Comment by lilleannette** [comment]
@AlfaAli I have requested a couple of changes  before it can be merged.
