### ISSUE TITLE
Add RUNID in input/output files names

### ISSUE THREAD

**Issue by AlfaAli** [nansencenter/NERSC-HYCOM-CICE#243]
This will include naming of both restart and archive files.

For example for TOPAZ5, instead of "archs.", arch files  will be name as "**TP5**archs.".
From now, "hycproj" will assume that filename base will start with the runid, for example **TP5**, **TP6**, **TP2**,...

**Comment by lilleannette** [comment]
@AlfaAli I was wondering if these changes are backwards compatible, i.e. will the code still work on all the files we have that do not have the "runid" at the beginning of the filename?

**Comment by AlfaAli** [comment]
Yes,  I have now pushed a new commit which will make hyc2proj backwards compatible, hence  it will also work with files named as  arch?.20??_???_??.?

**Comment by AlfaAli** [comment]
For example, these should:

_./hyc2proj archm.2024_166_04.a_
and
_./hyc2proj TP5archm.2024_166_04.a_

**Comment by lilleannette** [comment]
I have approved the pull request and will close the issue.
