### ISSUE TITLE
Relaxation timescale is hardcoded in rmunew

### ISSUE THREAD

**Issue by lilleannette** [nansencenter/NERSC-HYCOM-CICE#272]
The relaxation timescale i hard-coded in the program rmunew which is called by https://github.com/nansencenter/NERSC-HYCOM-CICE/blob/master/bin/relax_rmu.sh
No matter which timescale you give as input, it will make a file with a relaxation timescale of 20 days at the outer edge.

**Comment by Jipingnersc** [comment]
After checking the code of "renew," the timescale was fixed by 20 days because a small bug resulted in the input times scale not working.

**Comment by Jipingnersc** [comment]
In addition, the last input parameter indicates how many solo points are for relaxation. So, the previous test should be given 0 to avoid more input parameters.

**Comment by lilleannette** [comment]
Thanks, Jiping, I have approved the pull request and will close the issue.
